name: Java CI/CD with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Configure Git Identity
      run: |
        git config --global user.email "theoneste2060@gmail.com"
        git config --global user.name "Rich@gang61"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: ${{ secrets.G_TOKEN }}
        overwrite-settings: true

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/${{ github.theoneste2060 }}/my-spring-app:latest .
      working-directory: ${{ github.workspace }}

    - name: Login to GitHub Container Registry
      run: |
        echo ${{ secrets.G_TOKEN }} | docker login ghcr.io -u ${{ github.theoneste2060 }} --password-stdin
      env:
        DOCKER_HUB_USERNAME: ${{ github.theoneste2060 }}

    - name: Push Docker Image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.theoneste2060 }}/my-spring-app:latest
      env:
        DOCKER_HUB_USERNAME: ${{ github.theoneste2060 }}
