name: Java CI/CD with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Configure Git Identity
      run: |
        git config --global user.email "theoneste2060@gmail.com"
        git config --global user.name "Rich@gang61"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: ${{ secrets.G_TOKEN }}
        overwrite-settings: true

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Docker Image
      run: |
        docker build -t my-spring-app .
      working-directory: ${{ github.workspace }}

    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.Rich@gang61 }} | docker login -u ${{ secrets.theoneste61 }} --password-stdin
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.theoneste61 }}
        DOCKER_HUB_PASSWORD: ${{ secrets.Rich@gang61 }}

    - name: Push Docker Image to Docker Hub
      run: |
        docker tag my-spring-app ${{ secrets.theoneste61 }}/my-spring-app:latest
        docker push ${{ secrets.theoneste61 }}/my-spring-app:latest
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.theoneste61 }}
        DOCKER_HUB_PASSWORD: ${{ secrets.Rich@gang61 }}

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          my-spring-app.jar
        tag_name: latest
        token: ${{ secrets.GITHUB_TOKEN }}
