name: Java CI/CD with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Configure Git Identity
      run: |
        git config --global user.email "theoneste2060@gmail.com"
        git config --global user.name "Rich@gang61"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create Git Tag
      run: |
        git tag -a v1.0.0 -m "Version 1.0.0"
        git push origin v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          my-spring-app.jar
        tag_name: v1.0.0  # Use the tag you created
      token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-artifact
        path: my-spring-app.jar

    - name: Set Release Version
      run: echo "RELEASE_VERSION=${{ steps.create_release.outputs.version }}" >> $GITHUB_ENV

    - name: Archive Release
      run: |
        mkdir -p release-${RELEASE_VERSION}
        mv my-spring-app.jar release-${RELEASE_VERSION}/my-spring-app.jar
        zip -r release-${RELEASE_VERSION}.zip release-${RELEASE_VERSION}
      env:
        RELEASE_VERSION: ${{ steps.create_release.outputs.version }}
